language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
    - "pypy3"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - make init
    - pip install coveralls
    - pip install scrutinizer-ocular
script:
    - make test
after_success:
    - coveralls
    - ocular

